
@id=31688ad4-b125-4608-8372-87bf6ea40f05

PUT http://localhost:5001/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Vegan Sunshine V2",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}